// <auto-generated />
using LibraryManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LibraryManagement.Web.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20260628170000_AddUserRole")]
    partial class AddUserRole
    {
    }
}
