// <auto-generated />
using LibraryManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LibraryManagement.Web.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20260628173000_AddOrderStatus")]
    partial class AddOrderStatus
    {
    }
}
